name: uasdfinal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  google_maps_flutter: ^2.10.0
  provider: ^6.1.2
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.1.0
  webview_flutter: ^4.0.4
  url_launcher: ^6.3.1  
  youtube_player_flutter: ^9.1.1
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/mission_image.png
      - assets/vision_image.png
      - assets/values_image.png
      - assets/uasd_logo.png
      - assets/logo_app.png
      - assets/marcos.png
      - assets/vago1.jpg
      - assets/vago2.jpg
      - assets/vago3.jpg
      - assets/logo_blanco.png
      - assets/background.png
